# Generated by Django 2.2.4 on 2019-09-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaguebot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='account_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='player',
            name='riot_id',
            field=models.CharField(max_length=200),
        ),
    ]
