# Generated by Django 2.2.4 on 2019-09-29 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaguebot', '0003_auto_20190929_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='leaguebot.Player')),
                ('tft_tier', models.CharField(default='IRON', max_length=200)),
                ('tft_rank', models.CharField(default='V', max_length=200)),
                ('tft_lp', models.IntegerField(default=0)),
                ('tft_wins', models.IntegerField(default=0)),
                ('tft_losses', models.IntegerField(default=0)),
                ('solo_tier', models.CharField(default='IRON', max_length=200)),
                ('solo_rank', models.CharField(default='V', max_length=200)),
                ('solo_lp', models.IntegerField(default=0)),
                ('solo_wins', models.IntegerField(default=0)),
                ('solo_losses', models.IntegerField(default=0)),
                ('flex_tier', models.CharField(default='IRON', max_length=200)),
                ('flex_rank', models.CharField(default='V', max_length=200)),
                ('flex_lp', models.IntegerField(default=0)),
                ('flex_wins', models.IntegerField(default=0)),
                ('flex_losses', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='puuid',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
