# Generated by Django 2.2.4 on 2019-09-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaguebot', '0004_auto_20190929_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('blurb', models.TextField()),
                ('tag1', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('tag2', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('partype', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('hp', models.IntegerField()),
                ('hpperlevel', models.IntegerField()),
                ('mp', models.IntegerField()),
                ('mpperlevel', models.IntegerField()),
                ('movespeed', models.IntegerField()),
                ('armor', models.IntegerField()),
                ('armorperlevel', models.IntegerField()),
                ('spellblock', models.IntegerField()),
                ('spellblockperlevel', models.IntegerField()),
                ('attackrange', models.IntegerField()),
                ('hpregen', models.IntegerField()),
                ('hpregenperlevel', models.IntegerField()),
                ('mpregen', models.IntegerField()),
                ('mpregenperlevel', models.IntegerField()),
                ('crit', models.IntegerField()),
                ('critperlevel', models.IntegerField()),
                ('attackdamage', models.IntegerField()),
                ('attackdamageperlevel', models.IntegerField()),
                ('attackspeedoffset', models.IntegerField()),
                ('attackspeedperlevel', models.IntegerField()),
            ],
        ),
    ]
