# Generated by Django 2.2.4 on 2019-09-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaguebot', '0005_champion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champion',
            name='attackspeedoffset',
        ),
        migrations.AddField(
            model_name='champion',
            name='attackspeed',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='champion',
            name='armor',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='champion',
            name='armorperlevel',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='champion',
            name='attackdamage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='champion',
            name='attackdamageperlevel',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='champion',
            name='attackrange',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='champion',
            name='attackspeedperlevel',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='champion',
            name='crit',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='champion',
            name='critperlevel',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='champion',
            name='hp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='champion',
            name='hpperlevel',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='champion',
            name='hpregen',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='champion',
            name='hpregenperlevel',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='champion',
            name='movespeed',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='champion',
            name='mp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='champion',
            name='mpperlevel',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='champion',
            name='mpregen',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='champion',
            name='mpregenperlevel',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='champion',
            name='spellblock',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='champion',
            name='spellblockperlevel',
            field=models.FloatField(),
        ),
    ]
