# Generated by Django 2.2.3 on 2019-09-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('player', models.CharField(max_length=200)),
                ('turn', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('steamName', models.CharField(max_length=200)),
                ('slackNotification', models.BooleanField(default=True)),
                ('slackId', models.CharField(blank=True, max_length=200)),
                ('discordNotification', models.BooleanField(default=False)),
                ('discordId', models.CharField(blank=True, max_length=200)),
                ('emailNotification', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=200)),
            ],
        ),
    ]
