# Generated by Django 2.1 on 2019-09-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
