# Generated by Django 2.2.4 on 2019-09-28 23:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('civbot', '0002_game_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
